import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/layouts/incs/Header";
import Navbar from "@/layouts/incs/Navbar";
import Footer from "@/layouts/incs/Footer";

const inter = Inter({ subsets: ["latin"] });

const Layout = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title ?? "Trambet"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className} site`}>
        <Header />
        <div className="main-content">
          {children}
        </div>
        <Footer />
      </main>
    </>
  );
};

export default Layout;
