import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/layouts/incs/Header";
import Footer from "@/layouts/incs/Footer";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { usePathname } from "next/navigation";
import { useSelector } from "react-redux";
const inter = Inter({ subsets: ["latin"] });

const Layout = ({ title, children }) => {
  const router = useRouter();
  const pathname = usePathname();
  const authUser = useSelector((state) => state.AuthReducer);
  const { user } = authUser;

  // OTP verify process
  useEffect(() => {
    if (
      (pathname === "/auth/login" ||
        pathname === "/auth/one-click" ||
        pathname === "auth/register" ||
        pathname === "/register/affiliate") &&
      user
    ) {
      router.replace("/");
    }

    if (router?.asPath.startsWith("/?reference=") && !user) {
      router.replace(`/auth/register${router.asPath}`)
    }
    if (pathname === "/user/withdraw" && user && user?.kv != "1") {
      router.replace("/user/kyc-verification");
    }
    if (user && user?.email_verified == 0) {
      router.replace("/user/otp-verify");
    }
  }, [pathname]);

  return (
    <>
      <Head>
        <title>{title ?? "Trambet"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="format-detection"
          content="telephone=no, date=no, email=no, address=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className} site`}>
        <Header />
        <div className="main-content">{children}</div>
        <Footer />
      </main>
    </>
  );
};

export default Layout;
