name: Deploy to Cpanel
on:
  push:
    branches:
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          
      - name: Build Project
        run: |
          npm install 
          npm run build

      - name: Deploy to Cpanel
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.trambetbd.com
          username: trambetbd
          password: 3gUC#MShDjK1
          server-dir: public_html/
          local-dir: ./dist/